#+TITLE:Practicing one-dimensional arrays
#+STARTUP: overview hideblocks
#+PROPERTY: header-args:C :main yes :includes <stdio.h> :exports both :results output :comments both
* README

  * Practice workbook for one-dimensional arrays in C
  * See GitHub for script/solutions
* Emacs setup (optional)
** Hide emphatic characters like ~, *

   To *not* see the emphatic characters like ~ or * or / in the Org file
   text, run the following code chunk (or put the code in your ~/.emacs~
   file): if successful, you should see ~"t"~ in the minibuffer.

   #+begin_src emacs-lisp :results silent
     (setq-default org-hide-emphasis-markers t)
   #+end_src

   This will only work for new buffers. If you don't put it in your
   ~/.emacs~ file, the command will only work for the current Emacs
   session.

   *Close and reopen this file to see an effect.*

** Change your theme

   * In Emacs, type ~M-x custom-themes~
   * In the buffer that appears, select ~Leuven~
   * Select ~Apply and Save Setting~
   * This will work immediately

* Declare and initialize array

  * [ ] Declare two integer array ~foo~ of length ~5~ and initialize it
    with the values ~1,2,3,4,5~. Print the first and the last value of
    ~foo~.

    #+begin_src C
      int ???

      printf("%d %d", ???);
    #+end_src

* Sample program: reversing numbers

** Problem

   * Enter five numbers and print them in reverse order.
   * Store the numbers as one array.

** Solution

*** Input file

    You find the input file ~numbers~ in the ~arrays~ GDrive folder, or
    you can create it here.

    #+name: input
    #+begin_src bash :results silent
      echo '34 82 49 102 7' > numbers
    #+end_src

*** Code

    Fill in a few empty statements below:

    * [ ] At the top, define a macro ~N~ with the value ~5~

    * [ ] Declare an integer array ~a~ of length ~N~

    * [ ] Complete the ~scanf~ function inside the ~for~ loop to accept
      the array values

    * [ ] Complete the ~for~ loop to print the numbers: count down from
      ~N-1~ to ~0~.

    #+begin_src C :cmdline < numbers :tangle numbers.c
      ???   // define macro on this line

      ???   // declare array on this line
      int i;

      printf("Enter %d numbers: ", N);

      for (i = 0; i < N; i++) {
        scanf("%d", ???);   // complete scanf() function
       }
      printf("%d %d %d %d %d\n", a[0], a[1], a[2], a[3], a[4], a[5]);

      printf("In reverse order:");
      for ( ??? ) { // complete the for() expression
        printf(" %d", a[i]);
       }
      printf("\n");
    #+end_src
